- hosts: all
  become: yes
  vars:
    packeges:
      - apache2
      - tree
      - unzip
    hello: world
  tasks:
  - name: Install packeges
    ansible.builtin.apt:
      name: "{{ packeges }}"
      state: present  
      update_cache: yes 
    when: hello == "world"
      
  - name: Start service apache, if not started
    ansible.builtin.service:
      name: apache2
      state: started
      enabled: yes

  - name: Add the user tim ann brad
    ansible.builtin.user:
      name: "{{ item }}"
    loop:
      - tim
      - ann
      - brad

  #- name: Execute the command in remote shell; stdout goes to the specified file on the remote
  #  ansible.builtin.shell: useradd tim
